version: '3.8'

services:
  redis_cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpassword
    volumes:
      - redis_cache:/data

  postgres:
    image: postgres:15-alpine
    container_name: smarf_db_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "smarf_trading_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smarf_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d smarf_trading_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - redis_cache

volumes:
  postgres_data:
    driver: local
  redis_cache:
    driver: local

networks:
  smarf_network:
    driver: bridge
